email.username=mail@yandex.ru
email.password=password
email.from=my_mail@yandex.ru
mail.smtp.host=smtp.yandex.ru
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.ssl.enable=true
mail.smtp.starttls.enable=false
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.smtp.socketFactory.port=465